### ISSUE TITLE
LightweightMaps.gml tries to reference _toKeyName before it exists!

### ISSUE THREAD

**Issue by BPOutlaws** [dicksonlaw583/LightweightDataStructures#1]
Finally getting to check your data structure replacements (and learning how to use GitHub lol)  Line 11 in LightweightMaps.gml:
`var kn = _toKeyName(argument[i]);`
..calls _toKeyName before the static _toKeyName on line 17 and crashes the examples on the Simple Nested Map Example!  I just moved that loop down to be right under line 17 and it works fine now

**Comment by dicksonlaw583** [comment]
Patched for the upcoming release: https://github.com/dicksonlaw583/LightweightDataStructures/commit/b86536935ebbc22eb7e69faac7247d5eb24e7233
