### ISSUE TITLE
Problem with List.add()

### ISSUE THREAD

**Issue by dTrksak** [dicksonlaw583/LightweightDataStructures#2]
If I add more than one number to the list, it runs a while, then crashes. While debugging I saw this:
![Screenshot (51)](https://user-images.githubusercontent.com/60165871/87322156-af46bd80-c4f2-11ea-9e0c-392b9e05a294.png)
I'm not smart enough to debug this data structure on my own. I'm wondering if you get the same issue?

**Comment by dicksonlaw583** [comment]
That line is actually normal, I've skipped the first part of the `for` loop because `i` is already set up above that line. Can you provide an example of code that crashes?

**Comment by dTrksak** [comment]
The i isnt the issue, the issue is it breaks my game if I add two numbers to List().
It crashes when I do:
l = new List();
l.add(10); //No issues here
l.add(10); //Breaks here creating arrays inside arrays

I wasn't showing you that specific line, just the watch window on the left. See the arrays within arrays within _tail?
As far as I can tell, there isn't a specific line that causes the issue. I go to debug and even when I am paused on a line, it creates arrays within arrays. I didn't change anything inside the class either.

**Comment by dicksonlaw583** [comment]
It's supposed to create arrays pointing to other arrays, this is a double-linked list where the nodes are in array form.

Every array node has 3 entries:

- 0: The previous array node
- 1: The next array node
- 2: The value held at this node

Notice how the arrays always alternate between 2BE8000 (`_head`) and 2BE7F80 (`_tail`) when you navigate down. That's because the `_head` holds `[undefined, _tail, 50]` (no node before it, `_tail` is next, value is 50) and `_tail` holds `[_head, undefined, 100]` (previous node is the head, no node after it, value is 100). So with your two-entry list, if you navigate from the tail and alternate between index 0 and 1, you'll always hop back and forth between the tail and the head.

**Comment by dicksonlaw583** [comment]
By the way, which GMS 2.3 beta version are you on, and what export are you using? I'm using IDE 23.1.1.169 / Runtime 23.1.1.161 (open beta v11), and nothing is crashing on my system with your sample code: https://www.dropbox.com/s/237fo2oncld5mcm/github-lds-issue2-1.yyz?dl=1

**Comment by dTrksak** [comment]
Ahh, so it's not creating infinite arrays, it just seems like that in the debugger menu. A double-linked list eh? Pretty cool, now I understand the reason for all the arrays. The constant pointers throw me off though.

I am on the same version as you. I guess I have no idea why I'm crashing then. It only happens when I use the List class, the Grid works totally fine. It *could* be because I don't have all your scripts and stuff, just the stuff I need. If you don't have any problems, it's probably an issue of versions and what code I have of yours then, no big deal.

Oh and although the List class isn't working for me, the Grid class is amazing. I extended it with another constructor and am using it for a fairly complex inventory system that can remove and add grid items of any size or shape. Thanks a bunch for creating these data structures, really helped me out.

**Comment by dicksonlaw583** [comment]
As a precaution, please make sure that everything in the package is imported, even the structures you aren't actively using. If you use any of the load/save or serialization functions, please also make sure JSON Structs is in.

By any chance, are you using `string()` to view the list itself anywhere? That could be an infinite loop.

Another potential cause of the crash could be the garbage collector, which I have made reports for earlier last week. The symptoms of a GC-related crash is like you observed, OK initially but crashes a short time later. As an experiment, try **temporarily** turning off the GC with `gc_enable(false);` and see if it stops crashing (don't leave it there, it'll cause a global memory leak if you do). If it does, then it's a bug with the GC, which I hope they'll resolve in a future beta release.

Glad to hear that LDS is serving your project well. Good luck with it, and let me know if you find other bugs with LDS.
