### ISSUE TITLE
Could we get an example using List.sort()'s options in the Wiki?

### ISSUE THREAD

**Issue by BPOutlaws** [dicksonlaw583/LightweightDataStructures#4]
Any chance of throwing an example in the Wiki for how to use List.sort() with the keyer and comparer? ds_list_sort doesn't have those options to get an idea from and the description in the Wiki right now is kind of hard to figure out for how the syntax of using those would look!

**Comment by dicksonlaw583** [comment]
Added `keyer` and `comparer` examples to Wiki entries for `Grid.sort()` and `List.sort()`.
