### ISSUE TITLE
Crash when trying to resize grid

### ISSUE THREAD

**Issue by Juiin** [dicksonlaw583/LightweightDataStructures#5]
I got this Crash when trying to resize a grid, i believe i fixed it by changing this line 56 in LightweightGrids:
array_copy(newDataSize, 0, _data, 0, wh);
to this
array_copy(_newdata, 0, _data, 0, wh);

I believe this was a simple typo, if it was intended and the issue lies elsewhere please let me know:

local variable <unknown built-in variable>(-1610511209, -2147483648) not set before reading it.
 at gml_Script_anon_Grid_gml_GlobalScript_LightweightGrids_837_Grid_gml_GlobalScript_LightweightGrids (line 56) -                             array_copy(newDataSize, 0, _data, 0, wh);
############################################################################################
gml_Script_anon_Grid_gml_GlobalScript_LightweightGrids_837_Grid_gml_GlobalScript_LightweightGrids (line 56)
gml_Object_oController_Draw_0 (line 17) - depthgrid.resize( 2, max(1,inst_number));

**Comment by dicksonlaw583** [comment]
Thank you for reporting this bug. I have fixed this alongside another HTML5-related issue, and pushed up a new maintenance release.
