### ISSUE TITLE
'Malformed variable' when using ListIterator.value

### ISSUE THREAD

**Issue by Maarten0110** [dicksonlaw583/LightweightDataStructures#6]
Hi FrostyCat / @dicksonlaw583 ,
Thanks for making this very useful extension.
I get an error when using the `ListIterator.value` as `value` seems to be a built-in variable in GMS 2.3.
Changed it to something else in `LightweightLists.gml` and then it worked fine for me.
Maybe worth looking into for you?
Thanks again for the extension!

**Comment by dicksonlaw583** [comment]
What runtime and export are you using? The built-in test suites do make use of `ListIterator` [here](https://github.com/dicksonlaw583/LightweightDataStructures/blob/master/scripts/lds_test_list/lds_test_list.gml#L197), and I am not getting any errors in Runtime 2.3.1.409 using Windows VM or YYC.

**Comment by Maarten0110** [comment]
I have IDE v2.3.1.542 and Runtime v2.3.1.409.
The code editor also shows `value` as one of the autocomplete options, although I cannot read entirely what it belongs to:
![image](https://user-images.githubusercontent.com/15816387/105990066-45fb5600-60a2-11eb-8730-055c29433152.png)

**Comment by dicksonlaw583** [comment]
`value` is one of the keys in [keyframe structs](https://manual.yoyogames.com/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FSequences%2FSequence_Structs%2FThe_Keyframe_Data_Struct.htm) returned by sequence functions. It is not a reserved name in GML, and as such it is legal to name variables and struct keys as `value` outside of that context. Any error thrown from this is either user error or a bug in the compiler.

I have set up [a simple example](https://www.dropbox.com/s/lxsk5j952cg8mqs/lds_i6_sample1.yyz?dl=1) that uses `ListIterator.value`:

```
var list = new List("foo", "bar", "baz");
var str = "";
for (var it = list.iterator(); it.hasNext(); it.next()) {
	str += it.value + " ";
}
show_message_async(str);
```

I have tested this on IDE 2.3.1.542 / Runtime 2.3.1.409 on Windows and UWP (VM+YYC) and HTML5, but none of them are giving the error you described. If the error is coming from another export, please let me know.

**Comment by Maarten0110** [comment]
I tested it again in a fresh project and it indeed works fine. Went back to the other project and it now works fine there too. Must have been some error on my end then, my bad. Error messages in GMS are confusing sometimes. Thanks for the quick replies!
